from huggingface_hub import InferenceClient
from django.conf import settings


HF_MODEL = "Qwen/Qwen2.5-7B-Instruct"
MAX_CHARS_PER_CHUNK = 2500


print("⏳ Initializing Hugging Face InferenceClient...")
hf_client = InferenceClient(
    model=HF_MODEL,
    token=settings.HF_TOKEN,
)
print("✅ Hugging Face InferenceClient initialized")


def build_cleanup_prompt(raw_text: str) -> str:
    return f"""
You are a system specialized in cleaning and correcting university lecture transcripts generated by speech-to-text systems.

Your task is to improve the transcript while fully preserving its original meaning. You are NOT allowed to summarize or rewrite it.

 Strict Rules:

1. Language:
- The output must be entirely in Arabic.
- Do NOT write full sentences in English.
- If a technical term is needed, write it in Arabic first, then include the English term in parentheses.

2. Correction:
- Correct obvious transcription errors (distorted or misheard words).
- If a term is clearly recognizable from context, fix it properly.
- Do NOT leave broken or meaningless words (e.g., "ازهار", "النوم هول", "غراب").

3. Removal:
- Remove completely unintelligible words.
- Remove repetition.
- Remove irrelevant side comments (e.g., “guys”, “close the door”, background noise phrases).

4. Preserve content:
- Keep the same order of ideas.
- Do NOT summarize.
- Do NOT rewrite paragraphs in a new style.
- Do NOT add any new information.

5. Formatting:
- Split the text into clear sentences.
- Use paragraphs where appropriate.
- Add light punctuation to improve readability.

6. Handling unclear words:
- If a word can be confidently inferred → correct it.
- If a word is completely unclear → remove it.

 Goal:
Transform a noisy speech-to-text transcript into a clean, readable Arabic text while preserving the original content and meaning.

 Forbidden:
- Summarization
- Free rewriting
- Adding explanations
- Random English usage

 Required:
Same transcript, but cleaner and clearer.

Raw transcript:
{raw_text}
""".strip()


def clean_transcript_with_qwen_client(raw_text: str) -> str:
    if not raw_text or not raw_text.strip():
        return ""

    try:
        completion = hf_client.chat.completions.create(
            messages=[
                {
                    "role": "system",
                    "content": "You are a specialized tool for correcting and cleaning lecture transcripts generated by speech-to-text systems. Your task is conservative correction only, with no summarization and no free rewriting."
                },
               
                {
                    "role": "user",
                    "content": build_cleanup_prompt(raw_text)
                }
            ],
            temperature=0,
            max_tokens=1500,
        )

        cleaned_text = completion.choices[0].message.content.strip()
        return cleaned_text or raw_text

    except Exception as e:
        error_text = str(e)

        if "402" in error_text:
            print("⚠️ Hugging Face returned 402 Payment Required. Returning raw transcript.")
            return raw_text

        print(f"⚠️ Qwen cleanup via InferenceClient failed: {e}")
        return raw_text


def split_text_into_chunks(text: str, max_chars: int = MAX_CHARS_PER_CHUNK):
    text = (text or "").strip()
    if not text:
        return []

    chunks = []
    start = 0
    text_length = len(text)

    while start < text_length:
        end = min(start + max_chars, text_length)

        if end < text_length:
            last_space = text.rfind(" ", start, end)
            if last_space > start:
                end = last_space

        chunk = text[start:end].strip()
        if chunk:
            chunks.append(chunk)

        start = end

    return chunks


def clean_long_transcript_with_qwen_client(raw_text: str) -> str:
    chunks = split_text_into_chunks(raw_text, MAX_CHARS_PER_CHUNK)
    if not chunks:
        return ""

    cleaned_chunks = []

    for idx, chunk in enumerate(chunks, start=1):
        print(f"🧠 Cleaning transcript chunk {idx}/{len(chunks)} with InferenceClient...")
        cleaned_chunk = clean_transcript_with_qwen_client(chunk)
        cleaned_chunks.append(cleaned_chunk)

    return "\n".join(cleaned_chunks).strip()












